name: Go CI

on:
  push:
    branches:
      - stage
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.21 # Specify the Go version you are using

    - name: Install dependencies
      run: go mod tidy

    - name: Run tests
      run: go test example.com/price_calculator/tests
